import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
const root=new URL('../',import.meta.url);
const termPath=fileURLToPath(new URL('term.js',root));
const sitemapPath=fileURLToPath(new URL('sitemap.xml',root));
const source=fs.readFileSync(termPath,'utf8');
const match=source.match(/const concepts=(\{.*?\});\nconst facets=/s);
if(!match)throw new Error('Unable to locate concepts in term.js');
const concepts=Function(`"use strict";return (${match[1]})`)();
const terms=Object.values(concepts).flat();
if(terms.length!==750)throw new Error(`Expected 750 concepts, found ${terms.length}`);
const base='https://help.bestjustify.ir/';
const escapeXml=value=>String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
const today=new Date().toISOString().slice(0,10);
const urls=[base,...terms.map(term=>`${base}knowledge.html?term=${encodeURIComponent(term)}`)];
const body=urls.map(url=>`<url><loc>${escapeXml(url)}</loc><lastmod>${today}</lastmod></url>`).join('');
const xml=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${body}</urlset>\n`;
fs.writeFileSync(sitemapPath,xml,'utf8');
console.log(`Generated sitemap with ${urls.length} URLs.`);